-- Supabase schema for the Megu bot and dashboard.
-- Application data only: Poe2Watch and _prisma_migrations are intentionally excluded.

CREATE TYPE public."BotStatus" AS ENUM ('STARTING', 'RUNNING', 'STOPPING', 'STOPPED', 'ERROR');
CREATE TYPE public."VoiceAction" AS ENUM ('JOIN', 'LEAVE', 'MOVE');

CREATE TABLE public."GuildConfig" (
  "guildId" text PRIMARY KEY,
  "logChannelId" text,
  "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public."BotRuntime" (
  id integer PRIMARY KEY DEFAULT 1,
  status public."BotStatus" NOT NULL DEFAULT 'STOPPED',
  pid integer,
  "startedAt" timestamp(3) without time zone,
  "stoppedAt" timestamp(3) without time zone,
  "lastError" text,
  "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public."VoiceEvent" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "guildId" text NOT NULL,
  "userId" text NOT NULL,
  username text NOT NULL,
  action public."VoiceAction" NOT NULL,
  "channelId" text,
  "channelName" text,
  "fromChannelId" text,
  "fromChannelName" text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public."MusicHistory" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "guildId" text NOT NULL,
  title text NOT NULL,
  url text NOT NULL,
  "durationSec" integer,
  thumbnail text,
  uploader text,
  "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "VoiceEvent_guildId_createdAt_idx"
  ON public."VoiceEvent" ("guildId", "createdAt");
CREATE INDEX "MusicHistory_guildId_createdAt_idx"
  ON public."MusicHistory" ("guildId", "createdAt");

ALTER TABLE public."GuildConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BotRuntime" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."VoiceEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."MusicHistory" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public."GuildConfig", public."BotRuntime", public."VoiceEvent", public."MusicHistory" TO authenticated;
GRANT ALL ON public."GuildConfig", public."BotRuntime", public."VoiceEvent", public."MusicHistory" TO service_role;

CREATE POLICY "authenticated users can read guild config"
  ON public."GuildConfig" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated users can read bot runtime"
  ON public."BotRuntime" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated users can read voice events"
  ON public."VoiceEvent" FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated users can read music history"
  ON public."MusicHistory" FOR SELECT TO authenticated USING (true);
